### ISSUE TITLE
HTML/CSS

### ISSUE THREAD

**Issue by TimofeiShpak** [krisgsnv/digdes-homework#1]
https://github.com/krisgsnv/digdes-homework/blob/c3772b28a2e17e4f5cdc8d5628caa22db7978001/components/list-item/index.html#L19

лучше переносить конечный тег на новую строку, чтобы видеть где заканчивается

```
<span class="list-item__num">
    2653137653251836235432452513163168242748724298742287987322398742#
    123456s8901234567890123456sdd01234567890123ssa1231
</span>
```

просьба поправить во всех файлах

**Comment by TimofeiShpak** [comment]
https://github.com/krisgsnv/digdes-homework/blob/c3772b28a2e17e4f5cdc8d5628caa22db7978001/components/list-item/style.css#L25

просьба поменять на пиксели, так как на макетах размеры в пикселях

**Comment by krisgsnv** [comment]
Замечания исправлены [Коммит](https://github.com/krisgsnv/digdes-homework/commit/eb43c2be5e2c33df80c06b4587d82c894c8aaf25)
