### ISSUE TITLE
JS_webpack

### ISSUE THREAD

**Issue by TimofeiShpak** [krisgsnv/digdes-homework#2]
https://github.com/krisgsnv/digdes-homework/blob/8327110b122be18aff32c5fe6b96142b94ed7567/src/components/navigation/index.js#L2

просьба переписать путь с использованием "@" здесь и во всех остальных файлах

**Comment by TimofeiShpak** [comment]
https://github.com/krisgsnv/digdes-homework/blob/8327110b122be18aff32c5fe6b96142b94ed7567/src/js/index.js#L10

строки 10-19 лучше вынести в функцию, так код будет гибче

**Comment by krisgsnv** [comment]
Добавила пропущенные алиасы, вывод в index.js оформила отдельной функцией renderContent, которая выводит хедер и переданные ей элементы

**Comment by TimofeiShpak** [comment]
https://github.com/krisgsnv/digdes-homework/blob/c626d248dce461d69fc994d8fcfb914381ee06b7/src/scss/index.scss#L7

просьба переписать путь с использованием "@"

**Comment by TimofeiShpak** [comment]
файл handlers.js не используется, из-за чего обработчики не работают

**Comment by krisgsnv** [comment]
Поставила недостающие алиасы и пропущенный импорт
